apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./framework-repository.yaml
  - ./subscriptions-repository.yaml
  - ./apis-repository.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: graphman-repository-secret
  env: ./graphman-repository-secret.env
