apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-secret
  env: ./secret.env
- name: graphman-cluster-property-bundle
  files:
    - ./cluster-property.json
- name: restman-cluster-property-bundle
  files:
    - ./cluster-property.bundle