apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  labels:
    type: gcpsm
type: Opaque
stringData:
  secret-access-credentials: |-
    {
      "type": "service_account",
      "project_id": "slipstream-222523",
      "private_key_id": "e97411d5126e72af86ea5ff7c236b71dd5253b30",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDihoVJpvOM1b5e\nqZe/+OQMDgfEr0ZmeYUQzlFjqWaAft5jyVwEzALS2pV0PY3y+h04uJw9a059xza+\nMjsu/jmvVgME46463uD9Tdd/ZznsQl+n6RsgfOqZ6hjxKa3tcmTmnDAVGpzVbiPV\n9PjAfj0/HtJv2Fs2XJRRK8ngpE6wugOySUMxvv1NCX9E0yQ2cdA0UbdGBeI9EedS\nQaNOee2sV8LFwL+BxxxPS5u9pah1RSxdJJvTYRsrrvYtFrzan7X5Fc5oyg/u7AFZ\nykQlOVZ3clY+HZ6wBumbYfk0J+lYopJPmcpz6nhWXWWF2g7zJuL79ISHZQJc0Dxf\nij1oQ59XAgMBAAECggEAIIBoQmY7vqLHvYxRc3VnabAKVExJFRiYIOOsENke6w6I\n+RdMkSb2ZsDUaHO72Ld4lt6svYaWd1HXMcNCSPP9XIIXongf07Q5ODmW0wxWvBEq\nlAx3Bxp1N1/mc+pk2VNW/9w8F+MUH+69dzbpXrEeN4luwdEbW+Q8/EfZ9NXjsSkS\nPuUPGMBVR+XhDnTIEQa3ARKizssWJXsQIHqhxSPuiZ4cmdJOOvEOgBoQs1808cD5\nE2Eyn8CU4ag63DmYiVxTJmCKBXR39hIHcum120Vs9Z8HtNshUckOgusK8I1kGqkm\nqxIEVOVjnfqmrC1My3aG8sgqCZbj8MNMOK74fpUhAQKBgQD0pLF7xNB2HHImJiIK\nNfgwWI6BZtO1IuOvfh97U1KwhWzcivYq/zusf4oOwU1edPAMl7wXauasOWHzIDMY\nR0M7F2XBPqk0PQLzbROOusMyokTP0JJVgPyNo3RFzzx+5iosu6+Dk33KPyF2UeH8\nTRgZcFf/Hd0lL9pkGCujhG+DAQKBgQDtCoRq9h6qUl5N3xXWZzf4iR9GS3/ZsnGL\n+sWnJBpiRr1IW+Y5vpvJcMoU/5P9OBrbw0uhq/MSfSYwU5fqEFKY2u9xWQOvOgMm\nHr1W81qkH8Y2H0brYNMTWxt0vh84cVaK85ZeMU25mfTDsqNWEYToyoU+h6gxU/w4\nbbAW4xAaVwKBgQDA0rqNajBAl+UkynOUBrvLJ1GTDsAZChnZrZgUtTT8qv2FywWC\nGFApgxEG1jcsFxFJa6M19e1Am63nWl7LaQfFoIh0SvZElT4pLbT3j57g3uNLxQJB\n4HuvC8FOcKwm/TUKsxgAphTEfwPZ5WowWXeAPXsuOpSehdwlfqOOq4jVAQKBgFR+\nmD8MZlfuLoFxkPYxKulj74r+JJ+0FPeBt2zh2KnJb3VYlNNml1+R3eboR5dOpXxK\nvC3v/iBMDg3R7mfX06l6+TkdMswGUNMIyBMzgc7ZKK1oLr5+cB8JLdtKXhSfierT\n83i1+G+9altL1R879XWJoz9r2c9jkZeHueoenEHXAoGAbeDa+KT3vnFyZgbb8ezT\nugPCJZdZlIJe7zYyJ9WC6o1Sxb3uADHWFKwIBhvb9AudVOq09seOe22RNjty681X\n89MRwcv9XACF/YATv4TY64xnyJHILrMpiK7rmpKd6tvHKuErInGkYN3TX9QNz+d7\nCRJJLs9cbJXssRwmOj71XMg=\n-----END PRIVATE KEY-----\n",
      "client_email": "cloud-workshop-sa@slipstream-222523.iam.gserviceaccount.com",
      "client_id": "107843062111027708191",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/cloud-workshop-sa%40slipstream-222523.iam.gserviceaccount.com",
      "universe_domain": "googleapis.com"
    }