apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: graphman-otel-test-services
  files:
    - ./otel_test_services.json
- name: graphman-otel-message-complete
  files:
    - ./otel_message_complete.bundle