apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: api-requests
  name: api-requests
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: api-requests
    spec:
      containers:
      - command:
        - /bin/bash
        - /script.sh
        image: harbor.sutraone.com/dev/api-requests
        imagePullPolicy: IfNotPresent
        name: api-requests
        volumeMounts:
        - mountPath: /script.sh
          name: script
          subPath: script.sh
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 511
          items:
          - key: script
            path: script.sh
          name: send-api-requests-script
        name: script