apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: workshopuser(n)-eck
spec:
  image: otel/opentelemetry-collector-contrib:0.77.0
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      resource:
        attributes:
        - key: layer7gw.name
          value: "workshopuser(n)-ssg"
          action: upsert
    exporters:
      logging:
        loglevel: warn 
      otlp/elastic:
        endpoint: apm-server-apm-http.elastic.svc.cluster.local:8200
        tls:
          insecure_skip_verify: true
        headers:
          Authorization: "Bearer q85KTYR5jgFXWk196j2bI455"
      jaeger:
        endpoint: jaeger-cloud-workshop-collector-headless.observability.svc.cluster.local:14250
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: "0.0.0.0:8888"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resource,batch]
          exporters: [jaeger,otlp/elastic]
        metrics:
          receivers: [otlp]
          processors: [resource,batch]
          exporters: [otlp/elastic]
        logs: 
          receivers: [otlp]
          exporters: [otlp/elastic]