apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gcp-secret-manager/gcp-secret.yaml
  - ./gcp-secret-manager/secrets-store-gcp.yaml
  - ./gcp-secret-manager/external-secret-gcp-def.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: graphman-secret-reader-bundle
  files:
    - ./graphman-secret-reader-bundle.json
- name: private-key-secret
  files:
    - privatekey=./private.key